# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 043d798bca4b26d037ba501184189994dd1d4d1d82dfb9a89a1415ca966ce892679b2a74f8197bbd8a12759dfd17da6739016fc1b44d7df0e2d012411746687e
  admin_gmail_username: password.reminder.goes.here@gmail.com
  admin_help_name: adminisaur
  admin_help_email: adminisaur@somedomain.com
  admin_data_maven_name: datadactyl
  admin_data_maven_email: datadactyl@somedomain.com
  admin_code_name: 'Dave Morse'
  admin_code_email: admonsterator@somedomain.com

test:
  secret_key_base: b57866ceda6e3dae3f83c98fb06679ab541b299e7ce4ad1c9a81181ce7ca204fe4e88fd42c3e0facfe726398f4c10f73885c541d47e5e35d0223b5abf0d6bd74
  admin_gmail_username: password.reminder.goes.here@gmail.com
  admin_help_name: adminisaur
  admin_help_email: adminisaur@somedomain.com
  admin_data_maven_name: datadactyl
  admin_data_maven_email: datadactyl@somedomain.com
  admin_code_name: 'Dave Morse'
  admin_code_email: admonsterator@somedomain.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # used for sending password reminders:
  admin_gmail_username: <%= ENV["ADMIN_GMAIL_USERNAME"] %>
  admin_gmail_password: <%= ENV["ADMIN_GMAIL_PASSWORD"] %>
  # used for assisting users:
  admin_help_name: <%= ENV["ADMIN_HELP_NAME"] %>
  admin_help_mail: <%= ENV["ADMIN_HELP_MAIL"] %>
  # used for data integrity questions:
  admin_data_maven_name: <%= ENV["ADMIN_DATA_MAVEN_NAME"] %>
  admin_data_maven_mail: <%= ENV["ADMIN_DATA_MAVEN_MAIL"] %>
  # used for bugs and code:
  admin_code_name: <%= ENV["ADMIN_CODE_NAME"] %>
  admin_code_mail: <%= ENV["ADMIN_CODE_MAIL"] %>
